# Generated by Django 3.2.16 on 2023-01-19 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arena_cyber_sport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=60)),
                ('member_nick', models.CharField(max_length=10)),
                ('member_pic', models.ImageField(upload_to='member/')),
                ('member_position', models.CharField(choices=[('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], max_length=2)),
                ('member_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arena_cyber_sport.team')),
            ],
        ),
    ]
