# Generated by Django 3.2.16 on 2023-01-20 13:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('arena_cyber_sport', '0003_games_game_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='url',
            field=models.SlugField(default=django.utils.timezone.now, max_length=130, unique=True),
            preserve_default=False,
        ),
    ]
