# Generated by Django 3.2.16 on 2023-01-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena_cyber_sport', '0007_news_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.SlugField(default='qwer', max_length=130),
        ),
    ]
