# Generated by Django 3.2.16 on 2023-01-20 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arena_cyber_sport', '0008_alter_news_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='url',
        ),
    ]
